adjective = input("Please enter an adjective: ")
animal = input("Please enter the name of an animal: ")
verb1 = input("Please mention an action word: ")
exclamation = input("Please enter an exclamation word: ")
verb2 = input("please enter an action word different from the previous one: ")
verb3 = input("Please enter an entirely different action word: ")
verb4 = input("A past tense verb: ")
food_item = input("A food item: ")
verb5 = input("Another past tense verb: ")
adjective1 = input("An adjective: ")
verb6 = input("Another verb: ")
verb7 = input("A present continous verb: ")

print("****************************************")
a = ("The other day, I was really in trouble. It all started when I saw a very " + adjective + " " + animal + " " + verb1 + " down the hallway. " + '"' + exclamation.title() +'!"' + " I yelled. But all I could think to do was to " + verb2 + " over and over. Miraculously, that caused it to stop, but not before it tried to " + verb3 + " right in front of my family. It " + verb4 + " for a few meters and then ate the " + food_item + " that was on the table. Eventually, I " + verb5 + " that it was " + adjective1 + ". I should have let it " + verb6 + " by " + verb7 + " along its path.")
print(a)